### PR TITLE
the color of the nav bar was weird so i changed it (:

### PR DESCRIPTION
**Pull request by ZacheeNiyokwizera**
Plz review  and merge this.

### CODE REVIEW

**Comment by MYLESMUGISHA** [comment]
I like your idea of having the navbar color get changed but we can look for another color that looks more fancy than red , good catch

**Comment by ZacheeNiyokwizera** [comment]
Okay, Would you like me to use Green instead?

**Comment by ZacheeNiyokwizera** [comment]
or we can use white

**Comment by MYLESMUGISHA** [comment]
Yeah green or navy blue can be good to the Navbar instead

**Comment by ZacheeNiyokwizera** [comment]
Okay Thanks

**Pull request merged**
